name: Docker Hub

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000

    steps: 
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate local metadata for CI image
      id: meta_ci
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/okmo/hello-world

    - name: Generate push metadata for CI image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_ci_push
      uses: docker/metadata-action@v3
      with:
        images: |
          docker.io/okmo/hello-world

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build CI docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_ci.outputs.tags }}
        labels: ${{ steps.meta_ci.outputs.labels }}

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push CI docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/okmo/hello-world:${{ steps.meta_ci.outputs.version }}
        dst: ${{ steps.meta_ci_push.outputs.tags }}
